syntax = "proto3";

package movego.v1;

option go_package = "movego/gen/go/movego/v1;movegov1";

import "movego/v1/user.proto";
import "buf/validate/validate.proto";

service AuthService {
  rpc SignUp(SignUpRequest) returns (SignUpResponse);
  rpc SignIn(SignInRequest) returns (SignInResponse);
  rpc Refresh(RefreshRequest) returns (RefreshResponse);
  rpc SignOut(SignOutRequest) returns (SignOutResponse);
}

message SignUpRequest {
    string email = 1 [
        (buf.validate.field).string.email = true,
        (buf.validate.field).string.max_len = 255
    ];
    string password = 2 [
        (buf.validate.field).string.min_len = 8,
        (buf.validate.field).string.max_len = 72
    ];
    string user_agent = 3;
    string client_ip = 4;
}

message SignUpResponse {
    User user = 1;
    string access_token = 2;
    string refresh_token = 3;
}

message SignInRequest {
    string email = 1 [
        (buf.validate.field).string.email = true,
        (buf.validate.field).string.max_len = 255
    ];
    string password = 2 [
        (buf.validate.field).string.min_len = 8,
        (buf.validate.field).string.max_len = 72
    ];
    string user_agent = 3;
    string client_ip = 4;
}

message SignInResponse {
    User user = 1;
    string access_token = 2;
    string refresh_token = 3;
}

message RefreshRequest {
    string refresh_token = 1;
}

message RefreshResponse {
    string access_token = 1;
    string refresh_token = 2;
}

message SignOutRequest {
    string refresh_token = 1;
}

message SignOutResponse {}
