version: '3'

tasks:
  gen-proto:
    desc: Generate Go code from protobuf files
    cmd: buf generate
  push-proto:
    desc: Push proto files to buf registry
    cmds:
      - buf lint
      - buf push
  migrate-up:
    cmd: migrate -path services/user-service/db/migrations -database "postgres://postgres:postgres@localhost:5432/movego_user?sslmode=disable" up
  migrate-down:
    cmd: migrate -path services/user-service/db/migrations -database "postgres://postgres:postgres@localhost:5432/movego_user?sslmode=disable" down
