app:
  name: "movego-game"
  shutdown_timeout: "15s"
  log_level: "warn"

# database:
#   host: "postgres"
#   port: 5432
#   name: "movego_dev"
#   user: "postgres"
#   driver: "postgres"
#   ssl_mode: "require"
#   max_conn: 25

redis:
  addr: "redis:6379"
  username: redis
  db: 0
  pool_size: 50
  min_idle_conns: 10
  conn_max_idle_time: "5m"
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  max_retries: 3

server:
  host: "0.0.0.0"
  port: 8090
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "120s"
  shutdown_timeout: "15s"

otel:
  endpoint: "tempo:4317"
  metrics_port: 2121
