global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'movego-backend'
    static_configs:
      - targets: ['user-service:2112', 'game-service:2121', 'matchmaking-service:2102', 'notification-service:2132']
