// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveCredential = `-- name: SaveCredential :exec
INSERT INTO credentials (
    id,
    user_id,
    password_hash,
    provider,
    provider_key
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (id) DO UPDATE SET
    password_hash = EXCLUDED.password_hash,
    provider = EXCLUDED.provider,
    provider_key = EXCLUDED.provider_key
`

type SaveCredentialParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
	Provider     string      `json:"provider"`
	ProviderKey  pgtype.Text `json:"provider_key"`
}

func (q *Queries) SaveCredential(ctx context.Context, arg SaveCredentialParams) error {
	_, err := q.db.Exec(ctx, saveCredential,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.Provider,
		arg.ProviderKey,
	)
	return err
}
