// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	Delete(ctx context.Context, id uuid.UUID) error
	FindByID(ctx context.Context, id uuid.UUID) (Sessions, error)
	FindForAuth(ctx context.Context, arg FindForAuthParams) (FindForAuthRow, error)
	FindValid(ctx context.Context, id uuid.UUID) (FindValidRow, error)
	ListActiveByUserID(ctx context.Context, userID uuid.UUID) ([]Sessions, error)
	SaveCredential(ctx context.Context, arg SaveCredentialParams) error
	SaveSession(ctx context.Context, arg SaveSessionParams) error
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
