// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	SaveCredential(ctx context.Context, arg SaveCredentialParams) error
	SaveSession(ctx context.Context, arg SaveSessionParams) error
	SaveUser(ctx context.Context, arg SaveUserParams) error
}

var _ Querier = (*Queries)(nil)
