// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const delete = `-- name: Delete :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, delete, id)
	return err
}

const findValid = `-- name: FindValid :one
SELECT
    s.id, s.user_id, s.secret_hash, s.user_agent, s.client_ip, s.expires_at, s.created_at,
    u.id, u.email, u.tag, u.display_name, u.role, u.created_at, u.updated_at, u.deleted_at
FROM sessions s
INNER JOIN users u ON u.id = s.user_id
WHERE s.id = $1
  AND s.expires_at > now()
  AND u.deleted_at IS NULL
`

type FindValidRow struct {
	Sessions Sessions `json:"sessions"`
	Users    Users    `json:"users"`
}

func (q *Queries) FindValid(ctx context.Context, id uuid.UUID) (FindValidRow, error) {
	row := q.db.QueryRow(ctx, findValid, id)
	var i FindValidRow
	err := row.Scan(
		&i.Sessions.ID,
		&i.Sessions.UserID,
		&i.Sessions.SecretHash,
		&i.Sessions.UserAgent,
		&i.Sessions.ClientIp,
		&i.Sessions.ExpiresAt,
		&i.Sessions.CreatedAt,
		&i.Users.ID,
		&i.Users.Email,
		&i.Users.Tag,
		&i.Users.DisplayName,
		&i.Users.Role,
		&i.Users.CreatedAt,
		&i.Users.UpdatedAt,
		&i.Users.DeletedAt,
	)
	return i, err
}

const saveSession = `-- name: SaveSession :exec
INSERT INTO sessions (
    id,
    user_id,
    secret_hash,
    user_agent,
    client_ip,
    expires_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
    secret_hash = EXCLUDED.secret_hash,
    user_agent = EXCLUDED.user_agent,
    client_ip = EXCLUDED.client_ip,
    expires_at = EXCLUDED.expires_at
`

type SaveSessionParams struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"user_id"`
	SecretHash string    `json:"secret_hash"`
	UserAgent  string    `json:"user_agent"`
	ClientIp   string    `json:"client_ip"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.Exec(ctx, saveSession,
		arg.ID,
		arg.UserID,
		arg.SecretHash,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
