// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveSession = `-- name: SaveSession :exec
INSERT INTO sessions (
    id,
    user_id,
    secret_hash,
    user_agent,
    client_ip,
    expires_at,
    created_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (id) DO UPDATE SET
    secret_hash = EXCLUDED.secret_hash,
    user_agent = EXCLUDED.user_agent,
    client_ip = EXCLUDED.client_ip,
    expires_at = EXCLUDED.expires_at
`

type SaveSessionParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	SecretHash string             `json:"secret_hash"`
	UserAgent  string             `json:"user_agent"`
	ClientIp   string             `json:"client_ip"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SaveSession(ctx context.Context, arg SaveSessionParams) error {
	_, err := q.db.Exec(ctx, saveSession,
		arg.ID,
		arg.UserID,
		arg.SecretHash,
		arg.UserAgent,
		arg.ClientIp,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}
