// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const saveUser = `-- name: SaveUser :exec
INSERT INTO users (
    id,
    email,
    tag,
    display_name,
    role,
    created_at,
    updated_at,
    deleted_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (id) DO UPDATE SET
    email = EXCLUDED.email,
    tag = EXCLUDED.tag,
    display_name = EXCLUDED.display_name,
    role = EXCLUDED.role,
    updated_at = EXCLUDED.updated_at,
    deleted_at = EXCLUDED.deleted_at
`

type SaveUserParams struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Tag         string             `json:"tag"`
	DisplayName string             `json:"display_name"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) SaveUser(ctx context.Context, arg SaveUserParams) error {
	_, err := q.db.Exec(ctx, saveUser,
		arg.ID,
		arg.Email,
		arg.Tag,
		arg.DisplayName,
		arg.Role,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.DeletedAt,
	)
	return err
}
